### ISSUE TITLE
Reads the entire content or only the first lines of the web pages?

### ISSUE THREAD

**Issue by 6DiegoDiego9** [qunash/chatgpt-advanced#27]
Does it read the entire content of the web pages or only the first lines (those displayed in the prompt ending with "...") for each page?

**Comment by qunash** [comment]
For now it only returns the most semantically relevant excerpt from each page

**Comment by 6DiegoDiego9** [comment]
is "the most semantically relevant" the part that I see in the prompt?
or the real prompt is invisible and longer than the visible one?

**Comment by qunash** [comment]
Yes, it's only the parts that are returned from the backend.

**Comment by 6DiegoDiego9** [comment]
Ah, including the partial (truncated by "...") final sentences?

**Comment by msadjad** [comment]
Based on my own experiments and what I learned so far from OpenAIs documentation, basically, what the prompt is showing you is the entire thing that the model is receiving, no more, no less. 

So the `truncated` parts and the data inside the links are all **ignored** when it is returning the results.

**Comment by dsundmacher** [comment]
> For now it only returns the most semantically relevant excerpt from each page
Im hoping to grab the H1 - H4 Titles from web pages to build out similar outlines. Is there a reason for limiting what content is captured from each result? If this is due to server resources can this plugin be self hosted?  Im hoping chatbpt can use live data to better answer questions answered within websites it has never crawled before. Thanks
