### ISSUE TITLE
An error occurred Check the console for more details.

### ISSUE THREAD

**Issue by eggbest** [qunash/chatgpt-advanced#47]
I cannot use it,it said:

An error occurred
Check the console for more details.

**Comment by qunash** [comment]
Hi,
Please update the chatgpt page, try using the extension, and when the error occurs, open up the console (Ctrl+Shift+J). Then copy the contents of the console and write them here.

**Comment by eggbest** [comment]
mainUI.js:2569          GET https://ddg-webapp-aagd.vercel.app/search?max_results=3&q=Tell%20me%20why%20bilibili%20is%20a%20good%20investment%20now&time=d&region=wt-wt net::ERR_CONNECTION_RESET
apiSearch @ mainUI.js:2569
onSubmit @ mainUI.js:2616
mainUI.js:2640 WebChatGPT error --> API error:  TypeError: Failed to fetch
    at apiSearch (mainUI.js:2569:28)
    at HTMLButtonElement.onSubmit (mainUI.js:2616:31)



Web search results:

{web_results}
Current date: {current_date}

Instructions: Using the provided web search results, write a comprehensive reply to the given query. Make sure to cite results using [[number](URL)] notation after the reference. If the provided search results refer to multiple subjects with the same name, write separate answers for each subject.
Query: {query}

**Comment by qunash** [comment]
Does that happen all the time for you?

**Comment by MILKMILKKING** [comment]
> I cannot use it,it said:
> 
> An error occurred Check the console for more details.

I assume you are in mainland China, adding this address to your vpn list would solve the problem. https://ddg-webapp-aagd.vercel.app
我猜测你在中国大陆，将这个地址加入你的vpn名单中，可以解决这个问题。 https://ddg-webapp-aagd.vercel.app
@eggbest

**Comment by raviwarrier** [comment]
Hi. I am getting a similar error since 2 days now. I checked your instructions and here's what the console shows:

![image](https://user-images.githubusercontent.com/42061703/225526008-411bab10-92f0-4498-9274-eeeea122c9d0.png)

I am from India, so is there anything I should do?

This is the error I get every time. 

![image](https://user-images.githubusercontent.com/42061703/225526554-d3093156-778d-47dc-8dfb-ba1e91a1a227.png)

ChatGPT with the plugin disabled works fine. I am using Brave (updated to the latest release). I have tried this without any VPN (using Indian ISP) and it doesn't work. I tried using VPN (Mullvad) and it doesn't work even for Switzerland ISP. I have no proxies.

**Comment by qunash** [comment]
@raviwarrier does this happen on every request, or only with some prompts/commands?

**Comment by raviwarrier** [comment]
> @raviwarrier does this happen on every request, or only with some prompts/commands?

@qunash for every prompt, irrespective of what it may be.

**Comment by vsemoth** [comment]
If you have an ad blocker make sure it's disabled. Whitelist the ChatGPT page.
